services:
  caddy-deploy:
    networks:
      - proxy
    image: pknw1/product.pknw1.co.uk:latest
    container_name: caddy-product.pknw1.co.uk
    hostname: caddy-product.pknw1.co.uk
    environment:
      - VIRTUAL_HOST=product.pknw1.co.uk
      - VIRTUAL_PORT=80

networks:
  proxy:
    external: true
    name: proxy
